### PR TITLE
Fix deprecation warning about tty_size() on 0.5

### PR DESCRIPTION
**Pull request by nalimilan**
This solution is similar to that used in DataFrames.

### CODE REVIEW

**Comment by davidavdav** [comment]
Thanks.  I had just done this myself more or less.  I will merge and then re-arrange a bit. 

I am now reading the background information on A[1,:] change in 0.5.  Which is the next thing that causes the tests to fail for 0.5.

**Comment by nalimilan** [comment]
Thanks. One of the failures during the tests is due to a `Dict` being inferred as `Any` instead of `ASCIIString`, which I tracked down to https://github.com/JuliaLang/julia/issues/15911.

**Comment by davidavdav** [comment]
Yes, thanks, I fixed that in https://github.com/davidavdav/NamedArrays.jl/commit/2d4e56a194f5c9183f3aae0f58189eb1a16eba82 . 

I understand type inference is probably difficult, but it is really annoying that it doesn't always works. 

I have tried to make the indexing routines efficient by using very type-specific dicts, and have these types in the parameters of the NamedArray type.  But I find it sometimes hard to manage to get the type right for indices, especially with ascii and utf-8 being around simultaneously.

**Comment by nalimilan** [comment]
> I understand type inference is probably difficult, but it is really annoying that it doesn't always works.
> 
> I have tried to make the indexing routines efficient by using very type-specific dicts, and have these types in the parameters of the NamedArray type. But I find it sometimes hard to manage to get the type right for indices, especially with ascii and utf-8 being around simultaneously.

I think that's just a plain bug, it should be fixed before the release. Also, the distinction between `ASCIIString` and `UTF8String` is going to be removed soon (0.5 or 0.6).

**Pull request merged**
